### ISSUE TITLE
undefined method `can_create_deployment_keys_for_some_project' with Redmine 2.5.0.devel

### ISSUE THREAD

**Issue by oneclickdev** [kubitron/redmine_git_hosting#110]
Hello,

plugin is awesome. But I have an issue with editing users accounts. I get 404 when try to access URL like: 'users/ID/edit'
that happened on Redmine 2.4.+ and redmine_git_hosting 0.6.2 as well; so I upgraded everything to the latest versions but the problem still exists.

Logs says: 

``` log
Completed 500 Internal Server Error in 252.7ms

ActionView::Template::Error (undefined method `can_create_deployment_keys_for_some_project' for #<#<Class:0x00000007577220>:0x00000006aac840>):
    70:
    71:       <p><%= f.text_field :title, :label => :label_identifier_can_be_arbitrary, :required => true, :style => 'width: 97%;' %></p>
    72:
    73:       <% if @gitolite_public_key.key_type == 1 || can_create_deployment_keys_for_some_project(@user) %>
    74:         <div class="tabular">
    75:           <p>
    76:             <%= f.select :key_type, options_for_select(
  app/helpers/application_helper.rb:1041:in `labelled_form_for'
  app/views/common/_tabs.html.erb:22:in `block in _app_views_common__tabs_html_erb__646618160320960238_58003340'
  app/views/common/_tabs.html.erb:21:in `each'
  app/views/common/_tabs.html.erb:21:in `_app_views_common__tabs_html_erb__646618160320960238_58003340'
  app/helpers/application_helper.rb:318:in `render_tabs'
  app/views/users/edit.html.erb:9:in `_app_views_users_edit_html_erb__1335953419618740818_57847280'
```

here is what information on Redmine says: http://clip2net.com/s/6V5cAT

will be waiting for any information. thank you a lot!

**Comment by n-rodriguez** [comment]
Hi there!
I think this repo is not maintained any more, but you can test this fork : https://github.com/jbox-web/redmine_git_hosting ;)
