### ISSUE TITLE
redmine git hosting on redmine 2.0

### ISSUE THREAD

**Issue by gituser** [kubitron/redmine_git_hosting#52]
$ rake db:migrate_plugins RAILS_ENV=production --trace
*\* Invoke db:migrate_plugins (first_time)
*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
no such file to load -- dispatcher
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
/var/www/redmine/plugins/redmine_git_hosting/init.rb:50
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:251:in`require'
/var/www/redmine/lib/redmine/plugin.rb:129:in `load'
/var/www/redmine/lib/redmine/plugin.rb:120:in`each'
/var/www/redmine/lib/redmine/plugin.rb:120:in `load'
/var/www/redmine/config/initializers/30-redmine.rb:13
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in`load'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:236:in`load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.3/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/engine.rb:588
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/engine.rb:587:in`each'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/engine.rb:587
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:30:in`run'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:55:in `run_initializers'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:54:in`each'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/application.rb:136:in`initialize!'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in `send'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/railtie/configurable.rb:30:in`method_missing'
/var/www/redmine/config/environment.rb:14
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/application.rb:103:in `require'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/application.rb:103:in`require_environment!'
/var/lib/gems/1.8/gems/railties-3.2.3/lib/rails/application.rb:292:in `initialize_tasks'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in`call'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `execute'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:158:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:157:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:157:in`invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in`invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:116:in`invoke_task'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in`each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:66:in`run'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in`run'
/var/lib/gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
Tasks: TOP => db:migrate_plugins => redmine:plugins:migrate => environment

in new redmine plugins dir was moved from ~/vendors/plugins to ~/plugins
- there is no RAILS_ROOT anymore and no dispatcher :(

is there a quickfix for this?

Thanks

**Comment by kubitron** [comment]
Sigh.  Well, as the Readme says, this plugin is only for versions <= 1.3.  I need to do some work to make this work in later releases (including 1.4).  Thus, I have not even looked at Redmine 2.0.

Sounds like 2.0 is a bit more drastically rearranged. My guess that there is something far worse than what you are hung up on.  Looks like I have to redesign the Rakefiles.

Hopefully I'll have time soon.

**Comment by gituser** [comment]
Ye, I went back to older version of redmine and it seems its also not working for some reason. (Project directory is not created) - investigating right now..

_**> uninitialized constant GitHosting::GitoliteConfig::ADMIN_REPO
*__> /var/lib/gems/1.8/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:131:in `const_missing'
*__> /var/www/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:418:in `clone_or_pull_gitolite_admin'
*__> /var/www/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:691:in `update_repositories'
*__> /var/www/redmine/vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:31:in `set_update_active'
*__> /var/www/redmine/vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:48:in `bracketed_update_repositories'
*_*> git_hosting: update_repositories() failed

**Comment by gituser** [comment]
I think there is a problem with new gitolite3 as well...

:(

I have the same error as I had before it doesn't add keys to the authorized_keys.

Will try with gitolite2.

**Comment by kubitron** [comment]
This can be a gitolite installation problem... Try manually adding keys by altering the config file manually and pushing it...  Perhaps your permissions are wrong.

**Comment by gituser** [comment]
ok, i found the issue was I forgot to add users to the project :( (on redmine 1.3.x)

you probably need to add this to how-to as well, didnt try with gitolite3, on g2, but with few modifications it should work on g3 i think too.

Will wait for redmine 2.0.x support, dont close this issue please before support added.

**Comment by kubitron** [comment]
Um... This plugin won't add keys if there are no keys to add.

However, it _should_ create the repository even without users.  Is it not doing that?

**Comment by gituser** [comment]
Hi.

Yes it creates empty repository.

It doesn't add keys if there are no users added to the project.

I just thought it should be noted because someone could be in stuck due this.

**Comment by lutinwood** [comment]
Hi, 
I'm using  this plugin with the redmine's version 1.3 and gitolite 2 , I'm happy for the moment. I would like to prepare a migration to a newer version of redmine (2 or 1.4) . Do you think than we can imagine this plugin working with the latest redmine version (2 for instance) with (gitolite 3) or should I focus more on another couple (redmine 1.4, Gitolite 2). 

Thanks...
Jerry

**Comment by gituser** [comment]
it works just fine with 1.4 (i'm on it right now) but not with 2.0 as of yet.

**Comment by kubitron** [comment]
It doesn't really.  If you look, the settings are missing.  Also (more importantly), 1.4 allows more than one repo per project, and that really doesn't work.  Also, I think that there are other random incompatibilities.

1.4 is next on my list, after I catch fix some other bugs.  Next, 2.0 will get it.

If you want to try gitolite 3, I'd be curious whether that worked or not.

**Comment by gituser** [comment]
> It doesn't really. If you look, the settings are missing. Also (more importantly), 1.4 allows more than one repo per >project, and that really doesn't work. Also, I think that there are other random incompatibilities.

yeah, true, but for the first time it worked for me (without specific settings), now it gives me some weird plain-text page if i click on settings (i made repository default for this project).

> If you want to try gitolite 3, I'd be curious whether that worked or not.
> gitolite3 i tried but it didn't work for me because I didn't add relevant users to the repository.

gitolite2 works fine for me, g3's difference is there is 1 binary instead of multiple, so you'd need to change commands inside redmine_git_hosting as well.

**Comment by kubitron** [comment]
Ok.  Sorry to all about the delay on this issue. I got really busy for the last couple of months...

**Comment by gituser** [comment]
no worries, currently redmine_git_hosting works for me apart from settings  / my account

```
  Parameters: {"action"=>"account", "controller"=>"my"}
Rendering template within layouts/base
Rendering my/account

ActionView::TemplateError (undefined method `errors' for :gitolite_public_key:Symbol) on line #7 of vendor/plugins/redmine_git_hosting/app/views/my/account.html.erb:
4: </div>
5: <h2><%=l(:label_my_account)%></h2>
6: <%= error_messages_for 'user' %>
7: <%= error_messages_for :gitolite_public_key %>
8: 
9: <div class="splitcontentleft">
10:     <% labelled_form_for :user, @user, :url => { :action => "account" }, :html => { :id => 'my_account_form' } do |f| %>

    app/helpers/application_helper.rb:954:in `error_messages_for'
    app/helpers/application_helper.rb:954:in `map'
    app/helpers/application_helper.rb:954:in `error_messages_for'
    vendor/plugins/redmine_git_hosting/app/views/my/account.html.erb:7
    unicorn (4.3.1) lib/unicorn/http_server.rb:531:in `process_client'
    unicorn (4.3.1) lib/unicorn/http_server.rb:606:in `worker_loop'
    unicorn (4.3.1) lib/unicorn/http_server.rb:487:in `spawn_missing_workers'
    unicorn (4.3.1) lib/unicorn/http_server.rb:137:in `start'
    unicorn (4.3.1) bin/unicorn_rails:209
    /var/lib/gems/1.8/bin/unicorn_rails:19:in `load'
    /var/lib/gems/1.8/bin/unicorn_rails:19
```

happens if i go to my account

EDIT: fixed it just changed 

```
 <%= error_messages_for :gitolite_public_key %>
```

to

```
 <%= error_messages_for 'gitolite_public_key' %>
```

and it worked

**Comment by gituser** [comment]
another bug found: if i click on my account, then click on edit button on specific key and instead of cancel'ing or saving it i hit save button on the left it gives me a blank page.

**Comment by ghost** [comment]
Any news-planning  for this issue?

**Comment by kubitron** [comment]
Getting closer.  Cleaning up some random other issues.

**Comment by kubitron** [comment]
@gituser The second bug you found is actually a current bug, not just a Redmine.  Registering separate issue.

**Comment by ghost** [comment]
Thanks for your efforts much appreciated.

**Comment by gituser** [comment]
much appreciated, will test it more with g3 and report back.

**Comment by kubitron** [comment]
@gituser Ok.  testing branch should fix both the dispatcher problem you mentioned at the start of this bug and the weird problem with clicking on edit button for key followed by save on the left.

Try pulling and let me know what happens.  Not quite redmine 2.0, but will get there.

**Comment by kubitron** [comment]
Oh, @gituser, also fixed the gitolite_public_key error message issue you mentioned.  (on testing branch).

**Comment by ghost** [comment]
Hello kubitron!!

thanks for your job on redmine_git_hosting :) do you have any news about the compatibility with redmine 1.4?
let me know if you need help for testing ;)

thx

**Comment by kubitron** [comment]
News is that it is almost there.  Turns out that a number of changes happened in the 1.3=>1.4 transition that impacted the plugin.  Hopefully will have something to test within the next week.

**Comment by plsamuel** [comment]
It looks like other forks have started work on 2.0, I don't know if it would be mergeable though...

https://github.com/Liberty-Concepts/redmine_git_hosting/commit/da279fcac658038db51c864c216079620164c567

and the 2.0-migration branch of ericpaulbishop

**Comment by kubitron** [comment]
Hello.  I have been getting the plugin compatible with Redmine 1.4, which is a big step.  Afterwards, I'll start looking at 2.0.  I anyone is willing to try the 1.4 port, that would be good... (Still in an Alpha/Beta stage).

**Comment by kubitron** [comment]
What would be useful is for people to try out the Redmine 1.4 support, which is on my testing branch.

**Comment by gituser** [comment]
hi. sorry for silence, i'm gonna test this version today and report back.

many thanks

**Comment by kubitron** [comment]
No worries.  Probably good that you waited a day or so -- found a couple of bugs.

Let me know how it is working (and, of course -- register bugs individually so that I can track them).

**Comment by jimblanc** [comment]
Hey kubitron, I just wanted to thank you for your work on this. I've been trying to find a good git+redmine solution and this looks like the best bet. I'll try to contribute where I can (first by testing the 1.4 branch).

**Comment by kubitron** [comment]
@jimmyblanchard : Thanks.  Really appreciate it.

**Comment by lauer** [comment]
I don't have the time to look at i today, but maybe others could test if this branch actually works with redmine 2.0?
https://github.com/zucchi/redmine_git_hosting/commits/2.0-migration

If so, @kubitron could merge into this repository and save some time :) 

UPDATE: I just created a checkout of his repository into mine environment. And after running the setup again, it seems to work. I can now see changesets inside redmine again. 

  Redmine version                          2.1.2.stable.10544
  Ruby version                                1.9.3 (x86_64-linux)
  Rails version                                 3.2.8

**Comment by kubitron** [comment]
The current version 0.5.0x (for Redmine 1.4) is within epsilon of working with Redmine 2.0. I hope to have a 2.0-compatible version soon.  I take it that you are a potential tester?

**Comment by lauer** [comment]
Sure. As I wrote, zucchi's 2.0 branch does actually work kinda okay. I there is some errors.

**Comment by kubitron** [comment]
Ok.  Great!  Stay tuned.  (I take it that using Redmine 1.4 is out of the picture in the short term?)

**Comment by lauer** [comment]
Yes, I Can only test with Redmine 2.1 stable. 

Den 04/10/2012 kl. 17.18 skrev John Kubiatowicz notifications@github.com:

**Comment by gituser** [comment]
> Ok. Great! Stay tuned. (I take it that using Redmine 1.4 is out of the picture in the short term?)

no-no. there are still a lot of plugins incompatible with 2.0, so 1.4 is pretty stable and good.

**Comment by jimblanc** [comment]
Hey, I've been testing the "testing" branch with Redmine 1.4.x over the past few days and haven't encountered any problems yet. The lab that I work at is about to start using it on their Redmine install so it'll be more thoroughly tested in coming days.

**Comment by kubitron** [comment]
@jimmyblanchard : Ok.  Great!  Let me know.

This is now the master branch, incidentally (although I left the pointer in "testing" for a bit).  You might try switching your branch over to "master", since "testing" may go away soon.  If you find problems, please report them as new issues (since I like to track problems).

**Comment by lostar** [comment]
Is there any alpha(or pre alpha) version for 2.0? I'm going migrate our environment to 2.0 soon, so I can test and may be debug/develop but my ruby/rails knowledge is limited =).

**Comment by kubitron** [comment]
@lostar, not yet, but will be next on my list.  I pretty much know what needs to be done.  Just need to find time (and I have to get an environment, which is a bit of work, since Ruby 1.9/Rails 3.0 is not supported on Redhat Linux yet (my primary environment). Will probably start with Redmine 2.0, then update to 2.1 (second update requires switching from Prototype.js to jQuery.js, which requires work).

**Comment by lostar** [comment]
Thanks for information! Could you please roughly point me what code should be reworked? Maybe I can help you with something.

**Comment by TamiasSibiricus** [comment]
@kubitron What status of this issue? If yor need for develop environment for redmine 2.1 or 2.2 with gitolite 3 maybe i can help with it. I think there no sense adopt this plugin for redmine 2.0.

**Comment by lostar** [comment]
I've patch (without Rails 2.x support) that fix some basic issues, but some (critical) Rails routes didn't work yet. ModalBox also doesn't work. Moreover I didn't test some fixes because do not have appropriate environment (mirroring and so on). Redmine with this plugin (+patch) successfully start but as I mentioned work not finished yet...

**Comment by lauer** [comment]
I have switched away from this plugin, and are using native git support, and the Redmine Bitbucket plugin for external hosted git on BitBucket (switch also support internal private projects for free)

**Comment by TamiasSibiricus** [comment]
@lostar Thanks for your job! But where i can get code for tests? I don't see forks of this plugin in your profile or any redmine 2 compatible branch in this repo.

**Comment by qroac** [comment]
@lostar and others:
I'd provide a development environment with actual Redmine and Gitolite versions if needed.
Please send me a message if you are interested.

**Comment by lostar** [comment]
I've drop patch to gist: https://gist.github.com/26900afd89f2ee4f7b52
Right now I do not have time to finish it but hope soon I'll manage it. ;)

**Comment by TamiasSibiricus** [comment]
@lostar Please tell me on wich branch and on which commit i must apply this gist? Thanks

**Comment by lostar** [comment]
redmine 2.1.2
redmine_git_hosting: 64a881861936b3c27cdca32db465132b58082d55

**Comment by TamiasSibiricus** [comment]
@lostar Thanks for your reply. But when i try to apply gist diff for this commit i got:
tamias@Taurus:~/redmine_git_hosting$ git branch redmine2.2 64a881861936b3c27cdca32db465132b58082d55
tamias@Taurus:~/redmine_git_hosting$ git checkout redmine2.2
Switched to branch 'redmine2.2'
tamias@Taurus:~/redmine_git_hosting$ git apply ../gistfile1.diff
../gistfile1.diff:444: trailing whitespace.

../gistfile1.diff:519: trailing whitespace.
<%= labelled_remote_form_for @gitolite_public_key, 
../gistfile1.diff:541: trailing whitespace.
        $('input[type="submit"]').each(function() { 
../gistfile1.diff:625: trailing whitespace.
  <%= labelled_form_for :user, @user, 
../gistfile1.diff:778: trailing whitespace.
    match ':repo_path/*path', 
error: patch failed: app/controllers/deployment_credentials_controller.rb:79
error: app/controllers/deployment_credentials_controller.rb: patch does not apply

Maybe you point me to other commit. I just want start new branch from that point, apply your patch and after merging from master i want to try it on redmine 2.2

**Comment by ghost** [comment]
Hi!

Actually the patch works on the last revision if you don't apply deployment_credentials_controller and navigation sections from the patch.

deployment_credentials_controller must be patched by hand and navigation view has been deleted in last revisions, so no need to patch.

i forked the plugin and applied the patches.
I also did other corrections :  
- some named_scope/scope tests were missing, so rake db:migrate_plugins crashed at the end
- load ApplicationExt helper in settings controller

You can checkout it and test : https://github.com/jbox-web/redmine_git_hosting

**Comment by TamiasSibiricus** [comment]
@pitit-atchoum Yay... You have done great job. I would test your repo in next few days.on latest redmine stable

**Comment by crax** [comment]
i have tested  @pitit-atchoum 's branch, but not work well with redmine 2.2.3 and rails3. i have forked one and do some roughly fixing to let is work: https://github.com/crax/redmine_git_hosting.

@pitit-atchoum i have send you the pull request, you can merge it, although some codes is not very nice, however it works.

**Comment by letic** [comment]
Hey Crax I tested your fork but the repository edit link is broken.

I get the following : 

``` ruby
Started GET "/repositories/30/edit" at Tue Mar 05 13:07:50 +0000 2013
Processing by RepositoriesController#edit as HTML
  Parameters: {"id"=>"30"}
  Current user: letic (id=3)
  Rendered plugins/redmine_git_hosting/app/views/repositories/edit.html.erb within layouts/base (17.5ms)
Completed 500 Internal Server Error in 162ms

ActionController::RoutingError (No route matches {:controller=>"repositories", :id=>nil, :action=>"update"}):
```

I'm having a look if I can find the bug, but in the meantime if you could confirm if you have the same.

Cheers
LeTic

**Comment by ghost** [comment]
Hi!

I have integrated some patches from crax.
Can you test it please?
https://github.com/jbox-web/redmine_git_hosting

Thank you!

**Comment by letic** [comment]
Hey pitit-atchoum,

Thanks for the quick reply.

Your diff from crax tree seems minimal and does not address the routing error. It's the exact same behaviour and error. 

Cheers

**Comment by letic** [comment]
Hey guys,

I acutally thought I found the issue when I noticed that the @path variable sent to the controller was empty. The following diff got me past the above Exception :

``` ruby
diff --git a/app/views/repositories/edit.html.erb b/app/views/repositories/edit.html.erb
index fb51a4f..00ffb24 100644
--- a/app/views/repositories/edit.html.erb
+++ b/app/views/repositories/edit.html.erb
@@ -1,6 +1,6 @@
 <h2><%= l(:label_repository) %></h2>

-<%= labelled_form_for :repository, @repository, :url => repository_path(@path), :html => {:method => :put} do |f| %>
+<%= labelled_form_for :repository, @repository, :url => repository_path(@repository), :html => {:method => :put} do |f| %>
   <%= render :partial => 'form', :locals => {:f => f} %>
 <% end %>
```

Except that I ran into another one : 

``` ruby
Started GET "/repositories/28/edit" at Tue Mar 05 22:19:37 +0000 2013
Processing by RepositoriesController#edit as HTML
  Parameters: {"id"=>"28"}
  Current user: letic (id=3)
  Rendered plugins/redmine_git_hosting/app/views/repositories/_form.html.erb (5.6ms)
  Rendered plugins/redmine_git_hosting/app/views/deployment_credentials/_view_list.html.erb (1.3ms)
  Rendered plugins/redmine_git_hosting/app/views/repositories/edit.html.erb within layouts/base (8.6ms)
Completed 500 Internal Server Error in 17ms

ActionController::RoutingError (No route matches {:controller=>"deployment_credentials", :repository_id=>28, :action=>"create_with_key"}):
```

Even though the repository is correctly created in gitolite, it seems that it's not correctly configured in the redmine DB (for example it doesn't have a key for the update hooks, etc).

Is the plugin working for you ? 

Cheers 
Letic

**Comment by crax** [comment]
I'm using my version in company for several weeks, it works well, you guys can try it.

**Comment by letic** [comment]
Hey crax,

It is your version I am testing... as I said the edition of the repository doesn't work.

I thought it might be due to the migration of my existing repositories from redmine 1.3/redmine_git_hosting 0.4.5 to 2.2.3/0.5.1x but even with a clean DB I get the same error...

You can have a look yourself : http://projects.letic.fr:3000/projects/testgit/settings?tab=repositories (it's a dev install admin:admin) Click on edit : http://projects.letic.fr:3000/repositories/1/edit

And in the logs I get the same as explained above :

``` ruby
ActionController::RoutingError (No route matches {:action=>"update", :controller=>"repositories", :id=>nil}):
```

Any idea ?

Thanks
LeTic

**Comment by ghost** [comment]
Hi guys!

I got it!

Checkout and test!

https://github.com/jbox-web/redmine_git_hosting

Actually your problem resides in the way observers are set for Rails 3 in init.rb

This works :

```
if Rails::VERSION::MAJOR >= 3
  Rails.configuration.after_initialize do
    if !migrating_primary
      ActiveRecord::Base.observers << GitHostingObserver
      ActiveRecord::Base.observers << GitHostingSettingsObserver
      GitHostingObserver.instance.reload_this_observer
      GitHostingSettingsObserver.instance.reload_this_observer
    end
  end
else
```

but I strongly advise you to checkout or fork my repo, which contains a lot of code cleanup (mainly indentation) but also add a lot of consistency in the way the variables are set which eliminates a lot of bugs.

@letic your bug is fixed in my repo ;)

**Comment by letic** [comment]
Good man pitit-atchoum !

Your branch seems to solve the issue. I will do some further testing this morning and report back to you, but so far so good.

Cheers
LeTic

**Comment by letic** [comment]
Right... after further testing the edit screen is now accessible but all add operations from there are crashing as well... Can you work your magic again on this pitit-atchoum ? I wanted to have a go myslef but the diff is difficult to read with all the indentation change you did. 

You can see the issue here on the dev instance : http://projects.letic.fr:3000/repositories/1/edit 

Clicking on "Add Deployment Credential" : http://projects.letic.fr:3000/repositories/1/deployment-credentials/new throw : 

``` ruby
Started GET "/repositories/1/deployment-credentials/new" for 109.190.65.251 at Fri Mar 08 15:46:37 +0000 2013

ActionController::RoutingError (No route matches [GET] "/repositories/1/deployment-credentials/new"):
```

A similar exception is returned for all other link ("Add Post Receive URL", and "Add Repository Mirror").

LeTic

**Comment by ghost** [comment]
Fixed!
But be sure of cloning the good repo :) https://github.com/jbox-web/redmine_git_hosting

**Comment by letic** [comment]
That was quick :)

Well if you change repos everytime it's difficult to keep up :P

With this tree webrick doesn't even start up :

``` ruby
su web2 -c "ruby script/rails server webrick -e development"
=> Booting WEBrick
=> Rails 3.2.12 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
/usr/local/share/redmine/lib/redmine/scm/adapters/git_adapter.rb:26: warning: already initialized constant GIT_BIN
Exiting
/usr/local/share/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repository_patch.rb:18:in `included': uninitialized constant GitHosting::Patches (NameError)
        from /usr/local/share/redmine/plugins/redmine_git_hosting/lib/redmine_git_hosting/patches/repository_patch.rb:7:in `class_eval'
```

You need the following patch : 

``` ruby
diff --git a/lib/redmine_git_hosting/patches/repository_patch.rb b/lib/redmine_git_hosting/patches/repository_patch.rb
index 9689663..e56378a 100644
--- a/lib/redmine_git_hosting/patches/repository_patch.rb
+++ b/lib/redmine_git_hosting/patches/repository_patch.rb
@@ -15,7 +15,7 @@ module RedmineGitHosting
           has_one :git_extra, :foreign_key =>'repository_id', :class_name => 'GitRepositoryExtra', :dependent => :destroy

           # initialize association from git repository -> cia_notifications
-          has_many :cia_notifications, :foreign_key =>'repository_id', :class_name => 'GitCiaNotification', :dependent => :destroy, :extend => GitHosting::Patches::RepositoryC
+          has_many :cia_notifications, :foreign_key =>'repository_id', :class_name => 'GitCiaNotification', :dependent => :destroy, :extend => RedmineGitHosting::Patches::Repo

           # initialize association from repository -> deployment_credentials
           has_many :deployment_credentials, :dependent => :destroy
```

I am sending you a pull request.

I will continue my testing now that everything seems to be working.

Thanks for that
Cheers
LeTic

**Comment by n-rodriguez** [comment]
Thanks for your patch and sorry for all the moves in the project, but I think it was necessary to fix the last few bugs :)

I'm trying the plugin on Redmine 1.4.5... there are little weird bugs...

**Comment by letic** [comment]
Still get some errors when trying to add a mirror it seems the generic methods declared in app/helpers/application_ext_helper.rb are not available in view_list : 

``` ruby
Completed 500 Internal Server Error in 566ms

ActionView::Template::Error (undefined method `refspec' for #<#<Class:0x7fb09eaacf48>:0x7fb09e9b5a40>):
    29:                 <%= link_to(h(mirror.url), url_for(:controller => 'repository_mirrors', :action => 'edit', :repository_id => @repository.id, :id => mirror.id), :class => 'edit-mirror') %>
    30:               </td>
    31:               <td class="center" style="vertical-align:middle;"><%= refspec mirror, 64 %></td>
    32:               <td class="center" style="vertical-align:middle;"><%= mirror_mode mirror %><br/><%= checked_image mirror.active? %></td>
    33:               <td class="buttons" width="20%" style="vertical-align:middle;text-align:right;">
    34:                 <% if GitHostingHelper.can_edit_mirrors(@repository.project) %>
  plugins/redmine_git_hosting/app/views/repository_mirrors/_view_list.html.erb:32:in `_plugins_redmine_git_hosting_app_views_repository_mirrors__view_list_html_erb___1854112332_70198273607880'
```

I put some debug code in app/helpers/application_ext_helper.rb and the file is correctly loaded.

If I comment the line it will choke on the next one mirror_mode

**Comment by ghost** [comment]
I commit a temporary fix, I will finish it later.
Can you test it ?
Thanks for your help :)

Edit : got a 403 on deleting post receive urls and mirrors... i'll fix them later

can you test ohter aspects of the plugin please?

**Comment by letic** [comment]
I did a bit of testing and I'm now able to add a mirror.

Having a look around I noticed that when creating a brand new repositories they are created without the key in git_repository_extras so it's not present in the repository config file either and when pushing the repo to redmine I got infamous uninitialized repository page. 

Once the key has been added manually (in the DB and in the git config file) everything is working as expected. I think this is similar to https://github.com/ericpaulbishop/redmine_git_hosting/issues/89

**Comment by ghost** [comment]
I've fixed the 403 error on mirror and post receive urls deletion.
For the other issue, I'll take a look

**Comment by letic** [comment]
Yep I can confirm that the 403 are solved but the key creation issue is still there and is a fairly blocking one for new repositories.

Did you have a chance to have a look at it ?

I can still provide a test server if you require.

**Comment by ghost** [comment]
Can you give me access to your test server so I can do a quick test?

**Comment by letic** [comment]
Sure it's the same as in the above comments : http://projects.letic.fr:3000/

It's the dev instance with the default account/password : admin/admin

I do have a different behaviour compare to the production as I get a 403 when trying to create a mirror (not sure why as it is the same installation folder) but the missing repository key issue is the same on both prod and dev.

Feel free to add your public SSH key and commit if you wish. Without the repository key the hook are not working and the repository tab always shows the uninitialized page.

If you require an access to phpmyadmin that can be arrange, just send me your email address.

Thanks for your help
LeTic

**Comment by lostar** [comment]
Can I do some testing on your server? I'm going to create a user and a project and check some test cases. It should not make significant load on server.

**Comment by letic** [comment]
Well I thought it was obvious from my answer :)

This server had no load anyway go for it.

**Comment by lostar** [comment]
Thanks!

**Comment by lostar** [comment]
Can't assign public key (generated by ssh-keygen) for new user (lostar). Got "Internal Error".

**Comment by ghost** [comment]
I think I fixed it, can you git pull and test please?

For those who are testing my repo (https://github.com/jbox-web/redmine_git_hosting), you must delete your actual clone and re clone the repo, because the repo history has changed (re-fork from Kubitron)
No need to migrate db or something else (if it's already done)

@anarcat if you read this, sorry to have deleted the old repo, but I didn't want people to get confused with all this repos. Btw, you were right, that was not very ethical :)

**Comment by anarcat** [comment]
The merge works fine now, thanks for doing this, you did the right thing!!! :)

**Comment by n-rodriguez** [comment]
you're welcome :)

**Comment by ghost** [comment]
@letic : 

> > Having a look around I noticed that when creating a brand new repositories they are created without the key in  git_repository_extras so it's not present in the repository config file either and when pushing the repo to redmine I got infamous uninitialized repository page. 

Fixed in 878da9bedd3673816cafdb93266dc3228db5d09a

**Comment by letic** [comment]
@pitit-atchoum : Great stuff it works now. The plugin seems fully functional with Redmine 2.2.3 Everything I tested is working fine :
- Adding/Editing repositories
- Pushing to repository/See changesets in redmine's repository tab
- Adding/Editing Mirrors
- Pushing to mirrors 

For now deleting a repository doesn't remove it from gitolite, but it never worked for me before and it's quite painless to remove from gitolite manually anyway.

I'll let you know if I can find any bug. Maybe you should ask @kubitron to merge all your changes and label the plugin Redmine 2.X compatible :) 

I'll shut down the dev version of redmine if you do not need it anymore.

Cheers
LeTic

**Comment by ghost** [comment]
I'll shut down the dev version of redmine if you do not need it anymore.

Sure, and thanks for your help.

**Comment by n-rodriguez** [comment]
I did some litte fixes on my repo, so keep pulling :)
