### ISSUE TITLE
cannot load such file -- sys_helper

### ISSUE THREAD

**Issue by N4th4** [kubitron/redmine_git_hosting#65]
I'm getting the following error.

I only use this plugin. Works fine without.

redmine_git_hosting : commit d512172064
chiliproject : commit 080c5b63, version 3.0.0

```
$ RAILS_ENV=production rake db:migrate_plugins --trace
** Invoke db:migrate_plugins (first_time)
** Invoke db:migrate:plugins (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
cannot load such file -- sys_helper
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:184:in `require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:184:in `require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:291:in `require_or_load'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:250:in `depend_on'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:162:in `require_dependency'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/actionpack-2.3.14/lib/action_controller/helpers.rb:197:in `default_helper_module!'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/actionpack-2.3.14/lib/action_controller/helpers.rb:212:in `inherited_with_helper'
/home/chiliproject/chiliproject/app/controllers/sys_controller.rb:15:in `<top (required)>'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:184:in `require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:184:in `require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:291:in `require_or_load'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:250:in `depend_on'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:162:in `require_dependency'
/home/chiliproject/chiliproject/vendor/plugins/redmine_git_hosting/lib/git_hosting/patches/sys_controller_patch.rb:4:in `<top (required)>'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:184:in `require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:184:in `require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:291:in `require_or_load'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:250:in `depend_on'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:162:in `require_dependency'
/home/chiliproject/chiliproject/vendor/plugins/redmine_git_hosting/init.rb:60:in `block (2 levels) in evaluate_init_rb'
/home/chiliproject/chiliproject/vendor/plugins/redmine_git_hosting/init.rb:59:in `each'
/home/chiliproject/chiliproject/vendor/plugins/redmine_git_hosting/init.rb:59:in `block in evaluate_init_rb'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/rails/plugin.rb:158:in `eval'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/rails/plugin.rb:158:in `block in evaluate_init_rb'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/rails/plugin.rb:154:in `evaluate_init_rb'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/rails/plugin.rb:48:in `load'
/home/chiliproject/chiliproject/vendor/plugins/engines/lib/engines/plugin.rb:45:in `load'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/rails/plugin/loader.rb:38:in `block in load_plugins'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/rails/plugin/loader.rb:37:in `each'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/rails/plugin/loader.rb:37:in `load_plugins'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/initializer.rb:369:in `load_plugins'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/initializer.rb:165:in `process'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/initializer.rb:113:in `run'
/home/chiliproject/chiliproject/config/environment.rb:45:in `<top (required)>'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `block in require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:547:in `new_constants_in'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `require'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/gems/rails-2.3.14/lib/tasks/misc.rake:4:in `block in <top (required)>'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/home/chiliproject/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/chiliproject/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/chiliproject/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/chiliproject/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `load'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:19:in `<main>'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/bin/ruby_noexec_wrapper:14:in `eval'
/home/chiliproject/.rvm/gems/ruby-1.9.3-p194@chiliproject/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => db:migrate_plugins => db:migrate:plugins => environment
```

**Comment by kubitron** [comment]
Sorry for the delay.  Can you tell me more about your environment?    Which version of Ruby and Rails are you using?

It appears that perhaps this is an issue with using Ruby 1.9.3.  Is there any way that you could downgrade to Ruby 1.9.2 to see if it helps?

**Comment by kubitron** [comment]
Actually, are you sure that this version of Chiliproject works with Ruby 1.9.3?  I'm surprised....

**Comment by N4th4** [comment]
I'm using rvm (single-user installation), ruby version "ruby-1.9.3-p194", rails version 2.3.14.

On this https://www.chiliproject.org/projects/chiliproject/wiki/Installation , it is said that chiliproject is compatible with Ruby 1.9.2 and 1.9.3.

I will try to downgrade to 1.9.2 and post what I find.

**Comment by N4th4** [comment]
I downgarded to Ruby 1.9.2 and it works fine.

**Comment by kubitron** [comment]
Great!  Not sure why Chiliproject should work with 1.9.3 (usin Rails 2.3.14), but I'll investigate when I have more time.

I'm going to close this bug, if that is ok.

**Comment by mqu** [comment]
I have similar error with :
- Debian Wheezy,
- redmine from standard repository

can't find a way to fix that problem.

**Comment by kubitron** [comment]
Which version of Redmine and Ruby are you using?  Did you try using a version of Ruby < 1.9.3?

**Comment by mqu** [comment]
hello,
- I am using Debian Wheezy with current updates.
- redmine package claims to be version 1.4.4
- ruby : I have both version _(all this dependencies come from redmine package)_ : 
  - ruby1.8 package claims to be in 1.8.7.358-4
  - ruby1.9.1 claims to be version  _1.9.3.194-1_  (very strange)

I'm not Debian expert and have not yet tried to _downgrade_ to an other ruby version. I will have a look for that soon.

**Comment by mqu** [comment]
some news : creating a small **sys_helper.rb** in the right directory help :

```
cat > /usr/share/redmine/app/helpers/sys_helper.rb <<EOF
module SysHelper
end
EOF
```

seems to work fine now. I have been able to finish redmine + RGH (Redmine Git Hosting) on Debian wheezy. So nice !

**Comment by kubitron** [comment]
Hm.... Can you see if it works to put this file in:

```
vendor/plugins/redmine_git_hosting/app/helpers
```

instead?

**Comment by kubitron** [comment]
(p.s. to do the above experiment, make sure to remove it from the location you placed it in).

**Comment by mqu** [comment]
I will try this on monday.

**Comment by kubitron** [comment]
Ok.  When you do, just try removing the file that you added and pull from the testing branch.  I added that file myself.  The fact that it helped you suggests that 1.4.4 is compatible with Ruby 1.9.3, just controllers that I've patched which don't have helpers are a problem.  There is only one, namely sys_controller.

@N4th4 can you try pulling from the testing branch and upgrading to Ruby 1.9.3 again to see if it is fixed?

**Comment by mqu** [comment]
@kubitron : it's OK for _testing_ patch against _sys_controller_ error. I have some new error, but I think I should not use testing version with my current packages (Debian 7).

**Comment by kubitron** [comment]
So -- what is the error?  I am trying to trace down problems before I export this to my master branch...

**Comment by kubitron** [comment]
@mqu, please register the problem you alluded to as a bug if it is still occurring.
